#!/usr/bin/env bash
# reskin-character.sh — clone an existing Live2D character + recolor its
# texture atlases via ImageMagick. Preserves the rig 100% (UV coords stay
# identical) so the model still animates correctly.
#
# AI image generation cannot do this safely: it would shift atlas pieces
# off their UV-bound polygons and break Cubism rendering. ImageMagick's
# pixel-level transforms keep every piece exactly where the rig expects.
#
# Usage:
#   ./scripts/reskin-character.sh <source-id> <new-id> <preset>
#
# Presets (single-arg, KISS — extend the case below for new looks):
#   pink     brown → magenta-pink hair / pink skin
#   blue     brown → cyan-blue hair / icy skin
#   green    brown → mossy / matcha green
#   purple   brown → lavender purple
#   inverted negate colors → dark-mode silhouette
#
# Example:
#   ./scripts/reskin-character.sh hiyori hiyori-pink pink
set -euo pipefail

if [[ $# -lt 3 ]]; then
  echo "usage: $0 <source-id> <new-id> <preset:pink|blue|green|inverted>" >&2
  exit 1
fi

SRC_ID="$1"
NEW_ID="$2"
PRESET="$3"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/characters/$SRC_ID"
OUT="$ROOT/characters/$NEW_ID"

if [[ ! -d "$SRC" ]]; then
  echo "✗ source character not found: $SRC" >&2
  exit 1
fi
if [[ ! -f "$SRC/manifest.json" ]]; then
  echo "✗ source manifest missing: $SRC/manifest.json" >&2
  exit 1
fi

# ImageMagick: prefer `magick` (v7), fall back to `convert` (v6).
if command -v magick >/dev/null; then
  IM="magick"
elif command -v convert >/dev/null; then
  IM="convert"
else
  echo "✗ ImageMagick not installed (brew install imagemagick)" >&2
  exit 1
fi

echo "→ cloning $SRC_ID → $NEW_ID (preset=$PRESET)"
rm -rf "$OUT"
# Copy preserving symlinks; -R follows our state-dir symlinks via -L? No.
# We want symlinks to STAY symlinks (otherwise we'd duplicate the idle
# tree 4x). cp -a preserves symlinks.
cp -a "$SRC" "$OUT"

# Recolor every PNG inside the new character's texture directories.
# Live2D atlases are at <Model>.<size>/texture_*.png — find them all.
mapfile -t TEXTURES < <(find "$OUT/assets/states/idle" -name "*.png")
if [[ ${#TEXTURES[@]} -eq 0 ]]; then
  echo "✗ no PNG textures found under $OUT/assets/states/idle" >&2
  exit 1
fi

for tex in "${TEXTURES[@]}"; do
  echo "  · recoloring $(basename "$(dirname "$tex")")/$(basename "$tex")"
  # ImageMagick `-modulate brightness,saturation,hue` semantics: hue=100
  # is no rotation; hue=0 is -180°; hue=200 is +180°. The brown→? map
  # below was tuned by eyeballing texture_00.png on Hiyori — adjust the
  # hue value if you want a stronger / different shift.
  case "$PRESET" in
    pink)
      # Brown → magenta-pink. Hue 70 = -108° rotation around the wheel.
      "$IM" "$tex" -modulate 100,120,70 "$tex"
      ;;
    blue)
      # Brown → cyan-blue. Hue 200 = +180° rotation.
      "$IM" "$tex" -modulate 100,110,200 "$tex"
      ;;
    green)
      # Brown → mossy green / matcha. Hue 140 = +72°.
      "$IM" "$tex" -modulate 100,110,140 "$tex"
      ;;
    purple)
      # Brown → lavender / royal purple. Hue 50 = -180° darker side.
      "$IM" "$tex" -modulate 100,115,50 "$tex"
      ;;
    inverted)
      "$IM" "$tex" -channel RGB -negate +channel "$tex"
      ;;
    *)
      echo "✗ unknown preset: $PRESET" >&2
      exit 1
      ;;
  esac
done

# Patch manifest with new id + name. Keep everything else (motion mapping,
# states, license) so the variant inherits the source's behavior.
SRC_NAME=$(python3 -c "import json; print(json.load(open('$SRC/manifest.json'))['name'])")
NEW_NAME="$SRC_NAME · $PRESET"
python3 - <<PY
import json, pathlib
p = pathlib.Path("$OUT/manifest.json")
m = json.loads(p.read_text())
m["id"] = "$NEW_ID"
m["name"] = "$NEW_NAME"
m["description"] = "Recolor variant ($PRESET) of " + m.get("description", "")
p.write_text(json.dumps(m, indent=2) + "\n")
PY

cat > "$OUT/README.md" <<MD
# $NEW_NAME

Recolor variant of \`$SRC_ID\` (preset: **$PRESET**) generated by
\`scripts/reskin-character.sh\`. Same Live2D rig + motions; textures
recoloured via ImageMagick \`-modulate\` (preserves UV alignment).

Regenerate:
\`\`\`bash
./scripts/reskin-character.sh $SRC_ID $NEW_ID $PRESET
\`\`\`
MD

echo "✓ done. $NEW_ID installed at $OUT"
